version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: lucifery/wsc:latest
    deploy:
      replicas: 5 
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8000"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/data/redis/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
