version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: wsc-alpline:v7
    deploy:
      replicas: 5 
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
      - "84:50001"
    volumes:
      - /data/log:/web/WochuServerCenter/log
    networks:
      - webnet
networks:
  webnet:
